apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
      - name: orchestrator
        image: localhost:5000/dgfip-orchestrator
        ports:
          - containerPort: 8080
        env:
          - name: REDIS_HOST
            value: redis
        readinessProbe:
          httpGet:
            path: /utils/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3