apiVersion: v1
kind: Service
metadata:
  name: orchestrator-nodeport-service
spec:
  type: NodePort
  selector:
    app: orchestrator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080