version: '3.8'
services:
  orchestrator:
    build: ./orchestrator
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
  llm:
    build: ./llm
    environment:
          - REDIS_HOST=redis
  embeding:
    build: ./embeding
    environment:
          - REDIS_HOST=redis

  redis:
    image: "redis:alpine"
