name: Orchestrator docker Image CI

on:
  push:
    paths:
      - 'helm/**'
jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './helm'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: Update package lists
            run: sudo apt-get update

          - name: Install Helm
            run: |
              sudo apt install -y curl
              curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
              sudo chmod 700 get_helm.sh
              ./get_helm.sh

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.REGISTRY_TOKEN}}

          - name: 'login to Github container'
            run: echo ${{secrets.REGISTRY_TOKEN}} | helm registry login ghcr.io/lucassovre --username lucassovre --password-stdin

          - name: 'Send helm chart to GitHub Container Registry'
            run: |
              helm dependency update my-chart
              export LOCATION=$(helm package my-chart | awk '{print $NF}')
              helm push $LOCATION oci://ghcr.io/lucassovre