name: llm docker Image CI

on:
  push:
    paths:
      - 'llm/**'
jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './llm'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.REGISTRY_TOKEN}}

          - name: 'Build llm Image'
            run: |
              docker build . --tag ghcr.io/lucassovre/llmops-llm:latest
              docker push ghcr.io/lucassovre/llmops-llm:latest